name: ci

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: install dependencies
        run: npm install

      - name: lint
        run: npm run lint
  format:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: install dependencies
        run: npm install

      - name: format
        run: npm run format
